name: bug

description: report broken behavior

title: "bug: "

labels:
  - bug

body:
  - type: textarea
    id: steps
    attributes:
      label: steps
      description: exact steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: expected
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: actual
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: version
      placeholder: v0.0.1
